-- PostgreSQL persistence contract mirror for the .NET/EF Core backend.
-- IMPORTANT: this file is documentation/reference for an isolated environment.
-- The shared/backend database MUST be created and migrated by EF Core.
-- Do not run this file against the backend database after EF migrations exist.

CREATE SCHEMA IF NOT EXISTS leads;

CREATE TABLE IF NOT EXISTS leads."customers" (
    "CustomerId" uuid PRIMARY KEY,
    "Ciudad" text,
    "EmailNormalizado" text,
    "EmpresaId" bigint NOT NULL,
    "Nombre" varchar(250) NOT NULL,
    "TelefonoNormalizado" text
);
CREATE INDEX IF NOT EXISTS "IX_customers_EmpresaId_EmailNormalizado" ON leads."customers" ("EmpresaId", "EmailNormalizado");
CREATE INDEX IF NOT EXISTS "IX_customers_EmpresaId_TelefonoNormalizado" ON leads."customers" ("EmpresaId", "TelefonoNormalizado");

CREATE TABLE IF NOT EXISTS leads."leads" (
    "LeadId" bigint PRIMARY KEY,
    "Campania" text,
    "Canal" varchar(50) NOT NULL,
    "CanalNormalizado" text,
    "Ciudad" text,
    "CiudadNormalizada" text,
    "CustomerId" uuid,
    "Email" text,
    "EmailNormalizado" text,
    "EmpresaId" bigint NOT NULL,
    "EstadoGestion" varchar(30) NOT NULL,
    "FechaPrimerContacto" timestamptz,
    "FechaRegistro" timestamptz NOT NULL,
    "ModelMatchConfidence" numeric(5,4),
    "ModelMatchMethod" text,
    "ModeloInteresTexto" text,
    "ModeloTextoNormalizado" text,
    "MotorcycleSku" text,
    "NombreCliente" varchar(250) NOT NULL,
    "PuntoVentaId" bigint NOT NULL,
    "Telefono" text,
    "TelefonoNormalizado" text
);
CREATE INDEX IF NOT EXISTS "IX_leads_FechaRegistro" ON leads."leads" ("FechaRegistro");
CREATE INDEX IF NOT EXISTS "IX_leads_MotorcycleSku" ON leads."leads" ("MotorcycleSku");
CREATE INDEX IF NOT EXISTS "IX_leads_EmpresaId_PuntoVentaId" ON leads."leads" ("EmpresaId", "PuntoVentaId");

CREATE TABLE IF NOT EXISTS leads."advisors" (
    "AsesorId" bigint PRIMARY KEY,
    "Activo" boolean NOT NULL,
    "CapacidadDiariaLeads" integer NOT NULL,
    "EmpresaId" bigint NOT NULL,
    "FechaIngreso" timestamptz NOT NULL,
    "Nombre" varchar(250) NOT NULL,
    "PuntoVentaId" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_advisors_EmpresaId_PuntoVentaId_Activo" ON leads."advisors" ("EmpresaId", "PuntoVentaId", "Activo");

CREATE TABLE IF NOT EXISTS leads."motorcycles" (
    "Sku" text PRIMARY KEY,
    "Cilindraje" integer NOT NULL,
    "Linea" text NOT NULL,
    "Marca" text NOT NULL,
    "PrecioLista" numeric(18,2) NOT NULL,
    "PuntosVentaDisponibles" integer NOT NULL,
    "Segmento" text NOT NULL,
    "UnidadesDisponibles" integer NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_motorcycles_Marca_Linea" ON leads."motorcycles" ("Marca", "Linea");

CREATE TABLE IF NOT EXISTS leads."conversations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Canal" text NOT NULL,
    "ConversacionId" text NOT NULL,
    "FechaInicio" timestamptz NOT NULL,
    "LeadId" bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_conversations_ConversacionId" ON leads."conversations" ("ConversacionId");
CREATE INDEX IF NOT EXISTS "IX_conversations_LeadId" ON leads."conversations" ("LeadId");

CREATE TABLE IF NOT EXISTS leads."messages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Content" text NOT NULL,
    "ConversationId" bigint NOT NULL,
    "SenderType" text NOT NULL,
    "SentAt" timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_messages_ConversationId" ON leads."messages" ("ConversationId");

CREATE TABLE IF NOT EXISTS leads."lead_enrichments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Confianza" numeric(5,4) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "CuotaInicial" numeric,
    "FormaPago" text,
    "Intencion" text,
    "LeadId" bigint NOT NULL,
    "ModeloInteres" text,
    "Objecion" text,
    "PipelineVersion" text NOT NULL,
    "Provider" text NOT NULL,
    "SolicitoCita" boolean NOT NULL,
    "SolicitoCotizacion" boolean NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_lead_enrichments_LeadId_CreatedAt" ON leads."lead_enrichments" ("LeadId", "CreatedAt");

CREATE TABLE IF NOT EXISTS leads."lead_scores" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CreatedAt" timestamptz NOT NULL,
    "FinalScore" numeric(5,4) NOT NULL,
    "HistoricalProbability" numeric(5,4) NOT NULL,
    "LeadId" bigint NOT NULL,
    "ModelVersion" text NOT NULL,
    "Priority" varchar(20) NOT NULL,
    "ReasonsJson" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_lead_scores_LeadId_CreatedAt" ON leads."lead_scores" ("LeadId", "CreatedAt");

CREATE TABLE IF NOT EXISTS leads."lead_assignments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AsesorId" bigint NOT NULL,
    "AssignedAt" timestamptz NOT NULL,
    "LeadId" bigint NOT NULL,
    "Reason" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_lead_assignments_LeadId_AssignedAt" ON leads."lead_assignments" ("LeadId", "AssignedAt");

CREATE TABLE IF NOT EXISTS leads."pipeline_runs" (
    "RunId" uuid PRIMARY KEY,
    "Error" text,
    "FinishedAt" timestamptz,
    "PipelineVersion" varchar(100) NOT NULL,
    "RecordsFailed" integer NOT NULL,
    "RecordsProcessed" integer NOT NULL,
    "RecordsRead" integer NOT NULL,
    "StartedAt" timestamptz NOT NULL,
    "Status" varchar(30) NOT NULL,
    "SummaryJson" text
);
CREATE INDEX IF NOT EXISTS "IX_pipeline_runs_StartedAt" ON leads."pipeline_runs" ("StartedAt");
